import Navbar from '@components/Navbar';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='h-screen flex flex-col justify-center items-center'>
          <Navbar session={null} />
          {children}
        </main>
      </body>
    </html>
  );
}
// import "./globals.css";
// import Footer from "@components/layout/footer";
// import { Suspense } from "react";
// import type { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={cx(sfPro.variable, inter.variable)}>
//         <div className="fixed h-screen w-full bg-gradient-to-br from-indigo-50 via-white to-cyan-100" />
//         <Suspense fallback="...">
//           <Nav />
//         </Suspense>
//         <main className="flex min-h-screen w-full flex-col items-center justify-center py-32">
//           {children}
//         </main>
//         <Footer />
//         <Analytics />
//       </body>
//     </html>
//   );
// }
